name: gossamer_app
description: Decentralized Mesh Messenger
version: 1.0.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.82.6
  
  # Hardware
  flutter_blue_plus: ^1.34.5
  flutter_ble_peripheral: ^2.0.0
  permission_handler: ^11.3.1 # Slightly relaxed to ensure compatibility
  nfc_manager: ^3.5.0
  mobile_scanner: ^5.2.0
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  
  # Logic
  flutter_riverpod: ^2.5.1
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  unicons: ^2.0.0
  glass_kit: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^8.0.0

flutter:
  uses-material-design: true
